# TravisCI configuration for Automattic/phpcs-neutron-standard

if: "branch = master"

language: "php"
os:
  - "linux"
dist: "xenial"

php:
  - "8.0"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"

jobs:
  fast_finish: true

cache:
  directories:
    - "$HOME/.composer/cache"

script:
  - "composer validate --strict"
  - "composer update"
  - "composer test"
  - "composer lint"

notifications:
  email: false
