language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
  fast_finish: true

os:
  - linux

sudo: false

cache:
  directories:
    - vendor/

script:
  - composer install
  - composer test
  - composer lint

notifications:
  email: false
